export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const POST_LOADING = 'POST_LOADING';


//Tournament actions
export const REGISTER_TOUR = 'REGISTER_TOUR';
export const UNREGISTER_TOUR = 'UNREGISTER_TOUR';
export const GET_TOUR_INFO = 'GET_TOUR_INFO';
export const TOUR_LOADING = 'TOUR_LOADING';